/**
 * Futures calculator constants and market data
 */

// Futures market data
export const FUTURES_MARKETS = {
  ES: {
    name: 'S&P 500 E-Mini (ES)',
    category: 'Indices',
    contractSize: 50,
    tickSize: 0.25,
    tickValue: 12.5,
    pointValue: 50,
    margin: 15000,
    priceFormat: '4000.00',
    symbol: 'ES',
    exchange: 'CME',
    tradingHours: '17:00-16:00 CT (Sunday-Friday)',
    deliveryMonths: 'H,M,U,Z',
  },
  MES: {
    name: 'S&P 500 Micro E-mini (MES)',
    category: 'Indices',
    contractSize: 5,
    tickSize: 0.25,
    tickValue: 1.25,
    pointValue: 5,
    margin: 1500,
    priceFormat: '4000.00',
    symbol: 'MES',
    exchange: 'CME',
    tradingHours: '17:00-16:00 CT (Sunday-Friday)',
    deliveryMonths: 'H,M,U,Z',
  },
  NQ: {
    name: 'Nasdaq 100 E-Mini (NQ)',
    category: 'Indices',
    contractSize: 20,
    tickSize: 0.25,
    tickValue: 5.0,
    pointValue: 20,
    margin: 19000,
    priceFormat: '15000.00',
    symbol: 'NQ',
    exchange: 'CME',
    tradingHours: '17:00-16:00 CT (Sunday-Friday)',
    deliveryMonths: 'H,M,U,Z',
  },
  MNQ: {
    name: 'Nasdaq 100 Micro E-mini (MNQ)',
    category: 'Indices',
    contractSize: 2,
    tickSize: 0.25,
    tickValue: 0.5,
    pointValue: 2,
    margin: 1900,
    priceFormat: '15000.00',
    symbol: 'MNQ',
    exchange: 'CME',
    tradingHours: '17:00-16:00 CT (Sunday-Friday)',
    deliveryMonths: 'H,M,U,Z',
  },
  RTY: {
    name: 'Russell 2000 E-Mini (RTY)',
    category: 'Indices',
    contractSize: 50,
    tickSize: 0.1,
    tickValue: 5.0,
    pointValue: 50,
    margin: 8500,
    priceFormat: '2000.0',
    symbol: 'RTY',
    exchange: 'CME',
    tradingHours: '17:00-16:00 CT (Sunday-Friday)',
    deliveryMonths: 'H,M,U,Z',
  },
  M2K: {
    name: 'Russell 2000 Micro E-mini (M2K)',
    category: 'Indices',
    contractSize: 5,
    tickSize: 0.1,
    tickValue: 0.5,
    pointValue: 5,
    margin: 850,
    priceFormat: '2000.0',
    symbol: 'M2K',
    exchange: 'CME',
    tradingHours: '17:00-16:00 CT (Sunday-Friday)',
    deliveryMonths: 'H,M,U,Z',
  },
  YM: {
    name: 'Dow Jones E-Mini (YM)',
    category: 'Indices',
    contractSize: 5,
    tickSize: 1.0,
    tickValue: 5.0,
    pointValue: 5,
    margin: 10500,
    priceFormat: '35000',
    symbol: 'YM',
    exchange: 'CBOT',
    tradingHours: '17:00-16:00 CT (Sunday-Friday)',
    deliveryMonths: 'H,M,U,Z',
  },
  MYM: {
    name: 'Dow Jones Micro E-mini (MYM)',
    category: 'Indices',
    contractSize: 0.5,
    tickSize: 1.0,
    tickValue: 0.5,
    pointValue: 0.5,
    margin: 1050,
    priceFormat: '35000',
    symbol: 'MYM',
    exchange: 'CBOT',
    tradingHours: '17:00-16:00 CT (Sunday-Friday)',
    deliveryMonths: 'H,M,U,Z',
  },
  CL: {
    name: 'Crude Oil (CL)',
    category: 'Energy',
    contractSize: 1000,
    tickSize: 0.01,
    tickValue: 10.0,
    pointValue: 1000,
    margin: 5500,
    priceFormat: '80.00',
    symbol: 'CL',
    exchange: 'NYMEX',
    tradingHours: '17:00-16:00 CT (Sunday-Friday)',
    deliveryMonths: 'All months',
  },
  GC: {
    name: 'Gold (GC)',
    category: 'Metals',
    contractSize: 100,
    tickSize: 0.1,
    tickValue: 10.0,
    pointValue: 100,
    margin: 9900,
    priceFormat: '2000.0',
    symbol: 'GC',
    exchange: 'COMEX',
    tradingHours: '17:00-16:00 CT (Sunday-Friday)',
    deliveryMonths: 'G,J,M,Q,V,Z',
  },
};
