/* Autogenerated file. Do not edit manually. */
/* tslint:disable */

import type * as guestbookSol from './Guestbook.sol/index.js';
export type { guestbookSol };
import type * as lockSol from './Lock.sol/index.js';
export type { lockSol };
export * as factories from './factories/index.js';
export type { Guestbook } from './Guestbook.sol/Guestbook.js';
export { Guestbook__factory } from './factories/Guestbook.sol/Guestbook__factory.js';
export type { Lock } from './Lock.sol/Lock.js';
export { Lock__factory } from './factories/Lock.sol/Lock__factory.js';
