/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type { BaseContract, BigNumberish, BytesLike, FunctionFragment, Result, Interface, EventFragment, AddressLike, ContractRunner, ContractMethod, Listener } from "ethers"
import type { TypedContractEvent, TypedDeferredTopicFilter, TypedEventLog, TypedLogDescription, TypedListener, TypedContractMethod } from "../common.js"
  
export declare namespace Guestbook {
      
    export type MessageStruct = {author: AddressLike, content: string, timestamp: BigNumberish}

    export type MessageStructOutput = [author: string, content: string, timestamp: bigint] & {author: string, content: string, timestamp: bigint }
  
    }

  export interface GuestbookInterface extends Interface {
    getFunction(nameOrSignature: "getMessageCount" | "getMessages" | "messages" | "owner" | "signGuestbook" | "withdrawTips"): FunctionFragment;

    getEvent(nameOrSignatureOrTopic: "NewMessage" | "TipReceived"): EventFragment;

    encodeFunctionData(functionFragment: 'getMessageCount', values?: undefined): string;
encodeFunctionData(functionFragment: 'getMessages', values?: undefined): string;
encodeFunctionData(functionFragment: 'messages', values: [BigNumberish]): string;
encodeFunctionData(functionFragment: 'owner', values?: undefined): string;
encodeFunctionData(functionFragment: 'signGuestbook', values: [string]): string;
encodeFunctionData(functionFragment: 'withdrawTips', values?: undefined): string;

    decodeFunctionResult(functionFragment: 'getMessageCount', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'getMessages', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'messages', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'owner', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'signGuestbook', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'withdrawTips', data: BytesLike): Result;
  }

  
    export namespace NewMessageEvent {
      export type InputTuple = [author: AddressLike, content: string, timestamp: BigNumberish];
      export type OutputTuple = [author: string, content: string, timestamp: bigint];
      export interface OutputObject {author: string, content: string, timestamp: bigint };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

    export namespace TipReceivedEvent {
      export type InputTuple = [from: AddressLike, amount: BigNumberish];
      export type OutputTuple = [from: string, amount: bigint];
      export interface OutputObject {from: string, amount: bigint };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

  export interface Guestbook extends BaseContract {
    
    connect(runner?: ContractRunner | null): Guestbook;
    waitForDeployment(): Promise<this>;

    interface: GuestbookInterface;

    
  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined,
  ): Promise<Array<TypedEventLog<TCEvent>>>
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(event: TCEvent, listener: TypedListener<TCEvent>): Promise<this>
  on<TCEvent extends TypedContractEvent>(filter: TypedDeferredTopicFilter<TCEvent>, listener: TypedListener<TCEvent>): Promise<this>
  
  once<TCEvent extends TypedContractEvent>(event: TCEvent, listener: TypedListener<TCEvent>): Promise<this>
  once<TCEvent extends TypedContractEvent>(filter: TypedDeferredTopicFilter<TCEvent>, listener: TypedListener<TCEvent>): Promise<this>

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>
  removeAllListeners<TCEvent extends TypedContractEvent>(event?: TCEvent): Promise<this>


    
    
    getMessageCount: TypedContractMethod<
      [],
      [bigint],
      'view'
    >
    

    
    getMessages: TypedContractMethod<
      [],
      [Guestbook.MessageStructOutput[]],
      'view'
    >
    

    
    messages: TypedContractMethod<
      [arg0: BigNumberish, ],
      [[string, string, bigint] & {author: string, content: string, timestamp: bigint }],
      'view'
    >
    

    
    owner: TypedContractMethod<
      [],
      [string],
      'view'
    >
    

    
    signGuestbook: TypedContractMethod<
      [content: string, ],
      [void],
      'payable'
    >
    

    
    withdrawTips: TypedContractMethod<
      [],
      [void],
      'nonpayable'
    >
    


    getFunction<T extends ContractMethod = ContractMethod>(key: string | FunctionFragment): T;

    getFunction(nameOrSignature: 'getMessageCount'): TypedContractMethod<
      [],
      [bigint],
      'view'
    >;
getFunction(nameOrSignature: 'getMessages'): TypedContractMethod<
      [],
      [Guestbook.MessageStructOutput[]],
      'view'
    >;
getFunction(nameOrSignature: 'messages'): TypedContractMethod<
      [arg0: BigNumberish, ],
      [[string, string, bigint] & {author: string, content: string, timestamp: bigint }],
      'view'
    >;
getFunction(nameOrSignature: 'owner'): TypedContractMethod<
      [],
      [string],
      'view'
    >;
getFunction(nameOrSignature: 'signGuestbook'): TypedContractMethod<
      [content: string, ],
      [void],
      'payable'
    >;
getFunction(nameOrSignature: 'withdrawTips'): TypedContractMethod<
      [],
      [void],
      'nonpayable'
    >;

    getEvent(key: 'NewMessage'): TypedContractEvent<NewMessageEvent.InputTuple, NewMessageEvent.OutputTuple, NewMessageEvent.OutputObject>;
getEvent(key: 'TipReceived'): TypedContractEvent<TipReceivedEvent.InputTuple, TipReceivedEvent.OutputTuple, TipReceivedEvent.OutputObject>;

    filters: {
      
      'NewMessage(address,string,uint256)': TypedContractEvent<NewMessageEvent.InputTuple, NewMessageEvent.OutputTuple, NewMessageEvent.OutputObject>;
      NewMessage: TypedContractEvent<NewMessageEvent.InputTuple, NewMessageEvent.OutputTuple, NewMessageEvent.OutputObject>;
    

      'TipReceived(address,uint256)': TypedContractEvent<TipReceivedEvent.InputTuple, TipReceivedEvent.OutputTuple, TipReceivedEvent.OutputObject>;
      TipReceived: TypedContractEvent<TipReceivedEvent.InputTuple, TipReceivedEvent.OutputTuple, TipReceivedEvent.OutputObject>;
    
    };
  }